import type { Product, CommunityPost, RankingUser } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Sérum Vitamina C Premium',
    image: 'https://picsum.photos/seed/prod1/300/300',
    price: 89.90,
    category: 'beleza',
    supplier: 'Beauty Supply Co',
    rating: 4.8,
    salesCount: 12500,
    tiktokViews: 2300000,
    isViral: true,
    commission: 35,
    description: 'Sérum facial com vitamina C pura, ácido hialurônico e niacinamida.',
    supplierShips: true,
  },
  {
    id: '2',
    name: 'Whey Protein Isolado 900g',
    image: 'https://picsum.photos/seed/prod2/300/300',
    price: 149.90,
    category: 'saude',
    supplier: 'NutriMax Brasil',
    rating: 4.9,
    salesCount: 8700,
    tiktokViews: 1500000,
    isViral: true,
    commission: 25,
    description: 'Whey protein isolado com 30g de proteína por dose.',
    supplierShips: true,
  },
  {
    id: '3',
    name: 'Ring Light Profissional 18"',
    image: 'https://picsum.photos/seed/prod3/300/300',
    price: 199.90,
    category: 'tech',
    supplier: 'TechStore Direct',
    rating: 4.7,
    salesCount: 6200,
    tiktokViews: 890000,
    isViral: true,
    commission: 30,
    description: 'Ring light profissional com tripé ajustável e suporte para celular.',
    supplierShips: true,
  },
  {
    id: '4',
    name: 'Cinta Modeladora Térmica',
    image: 'https://picsum.photos/seed/prod4/300/300',
    price: 79.90,
    category: 'fitness',
    supplier: 'FitWear Brasil',
    rating: 4.6,
    salesCount: 15800,
    tiktokViews: 4200000,
    isViral: true,
    commission: 40,
    description: 'Cinta modeladora com efeito térmico para treinos.',
    supplierShips: true,
  },
  {
    id: '5',
    name: 'Kit Skincare Coreano',
    image: 'https://picsum.photos/seed/prod5/300/300',
    price: 129.90,
    category: 'beleza',
    supplier: 'K-Beauty Import',
    rating: 4.9,
    salesCount: 9300,
    tiktokViews: 3100000,
    isViral: true,
    commission: 38,
    description: 'Kit completo de skincare com 7 etapas da rotina coreana.',
    supplierShips: true,
  },
  {
    id: '6',
    name: 'Curso Dropshipping Avançado',
    image: 'https://picsum.photos/seed/prod6/300/300',
    price: 297.00,
    category: 'digital',
    supplier: 'Liberdade Academy',
    rating: 4.8,
    salesCount: 3200,
    isViral: false,
    commission: 50,
    description: 'Curso completo de dropshipping com estratégias avançadas.',
    supplierShips: false,
  },
  {
    id: '7',
    name: 'Colágeno Hidrolisado Verisol',
    image: 'https://picsum.photos/seed/prod7/300/300',
    price: 69.90,
    category: 'saude',
    supplier: 'VitaLab',
    rating: 4.7,
    salesCount: 11200,
    tiktokViews: 1800000,
    isViral: true,
    commission: 32,
    description: 'Colágeno hidrolisado tipo I com tecnologia Verisol.',
    supplierShips: true,
  },
  {
    id: '8',
    name: 'Luminária LED Smart WiFi',
    image: 'https://picsum.photos/seed/prod8/300/300',
    price: 159.90,
    category: 'casa',
    supplier: 'SmartHome BR',
    rating: 4.5,
    salesCount: 4500,
    tiktokViews: 720000,
    isViral: true,
    commission: 28,
    description: 'Luminária inteligente com controle por app e Alexa.',
    supplierShips: true,
  },
  {
    id: '9',
    name: 'Tênis Esportivo Ultra Boost',
    image: 'https://picsum.photos/seed/prod9/300/300',
    price: 249.90,
    category: 'moda',
    supplier: 'SneakerDrop',
    rating: 4.8,
    salesCount: 7800,
    tiktokViews: 2600000,
    isViral: true,
    commission: 22,
    description: 'Tênis esportivo com amortecimento ultra boost.',
    supplierShips: true,
  },
  {
    id: '10',
    name: 'Kit Maquiagem Completo',
    image: 'https://picsum.photos/seed/prod10/300/300',
    price: 189.90,
    category: 'beleza',
    supplier: 'MakeUp Pro',
    rating: 4.6,
    salesCount: 5600,
    tiktokViews: 1400000,
    isViral: true,
    commission: 35,
    description: 'Kit profissional com paleta, pincéis e fixador.',
    supplierShips: true,
  },
];

export const MOCK_POSTS: CommunityPost[] = [
  {
    id: '1',
    author: { id: '2', name: 'Ana Clara', level: 15 },
    content: 'Galera, fiz minha primeira venda de R$500 hoje usando o catálogo! O sérum de vitamina C tá bombando no TikTok. Quem quiser dicas, comenta aqui! 🚀',
    likes: 234,
    comments: 45,
    isLiked: false,
    createdAt: '2026-08-06T10:30:00Z',
    category: 'resultado',
  },
  {
    id: '2',
    author: { id: '3', name: 'Lucas Mendes', level: 22 },
    content: 'Dica de ouro: foquem em produtos com mais de 1M de views no TikTok. A taxa de conversão é 3x maior! Semana passada faturei R$3.200 só com 2 produtos virais.',
    likes: 567,
    comments: 89,
    isLiked: true,
    createdAt: '2026-08-05T14:20:00Z',
    category: 'dica',
  },
  {
    id: '3',
    author: { id: '4', name: 'Mariana Silva', level: 8 },
    content: 'Acabei de entrar e já estou impressionada com o catálogo! Mais de 3 mil produtos validados? Como vocês escolhem os melhores pra começar?',
    likes: 89,
    comments: 32,
    isLiked: false,
    createdAt: '2026-08-05T09:15:00Z',
    category: 'duvida',
  },
  {
    id: '4',
    author: { id: '5', name: 'Pedro Oliveira', level: 30 },
    content: 'Batemos a meta do mês! R$15.000 em vendas só com dropshipping. Sem estoque, sem logística. O fornecedor envia direto pro cliente. Essa é a liberdade!',
    likes: 892,
    comments: 156,
    isLiked: true,
    createdAt: '2026-08-04T18:45:00Z',
    category: 'resultado',
  },
  {
    id: '5',
    author: { id: '6', name: 'Juliana Costa', level: 18 },
    content: 'Não desistam! Meu primeiro mês fiz apenas R$200. No terceiro mês já estava em R$5.000. Consistência é a chave! 💪',
    likes: 445,
    comments: 67,
    isLiked: false,
    createdAt: '2026-08-04T12:00:00Z',
    category: 'motivacao',
  },
];

export const MOCK_RANKING: RankingUser[] = [
  { id: '5', name: 'Pedro Oliveira', level: 30, xp: 15200, rank: 1, salesCount: 342, badge: '👑' },
  { id: '3', name: 'Lucas Mendes', level: 22, xp: 9800, rank: 2, salesCount: 256, badge: '🏆' },
  { id: '6', name: 'Juliana Costa', level: 18, xp: 7500, rank: 3, salesCount: 198, badge: '🥉' },
  { id: '2', name: 'Ana Clara', level: 15, xp: 5400, rank: 4, salesCount: 145 },
  { id: '7', name: 'Rafael Santos', level: 14, xp: 4900, rank: 5, salesCount: 132 },
  { id: '1', name: 'Thais Maximiana', level: 12, xp: 2450, rank: 6, salesCount: 87 },
  { id: '8', name: 'Camila Rocha', level: 11, xp: 2100, rank: 7, salesCount: 76 },
  { id: '9', name: 'Bruno Almeida', level: 10, xp: 1800, rank: 8, salesCount: 64 },
  { id: '10', name: 'Fernanda Lima', level: 9, xp: 1500, rank: 9, salesCount: 52 },
  { id: '11', name: 'Diego Martins', level: 8, xp: 1200, rank: 10, salesCount: 41 },
];

export const CATEGORIES = [
  { id: 'todos', label: 'Todos', icon: 'apps' as const },
  { id: 'beleza', label: 'Beleza', icon: 'flower' as const },
  { id: 'saude', label: 'Saúde', icon: 'fitness' as const },
  { id: 'fisico', label: 'Físicos', icon: 'cube' as const },
  { id: 'digital', label: 'Digital', icon: 'cloud-download' as const },
  { id: 'moda', label: 'Moda', icon: 'shirt' as const },
  { id: 'casa', label: 'Casa', icon: 'home' as const },
  { id: 'tech', label: 'Tech', icon: 'hardware-chip' as const },
  { id: 'fitness', label: 'Fitness', icon: 'barbell' as const },
];
